### ISSUE TITLE
better error message for failing dune release tag

### ISSUE THREAD

**Issue by hannesm** [samoht/dune-release#115] opened 2018-10-26 15:39 UTC
I get (with dune-release.1.1.0):
```
$ dune-release tag
dune-release: [ERROR] ['git' '--git-dir' '.git' 'tag' '-a' '-m' 'Distribution
                      0.4.0' '0.4.0'
                       'HEAD'] exited with code 128
```

which happened to me when the tag 0.4.0 already existed.

**Comment by NathanReb** [comment] 2019-11-22 13:28
This is a duplicate of #122, will fix soon, thanks for reporting!

I'm closing this.

**Closed by NathanReb** 2019-11-22 13:28 UTC
