### ISSUE TITLE
doc publishing doesn't copy files to the root level of gh-pages

### ISSUE THREAD

**Issue by anuragsoni** [samoht/dune-release#94] opened 2018-09-25 01:00 UTC
Maybe i missed some configuration, but during publishing `dune-release` is copying the `_html` folder into the root of gh-pages branch. Since there is no `index.html` in the directory github pages doesn't pick it up.

Example: https://github.com/anuragsoni/color/tree/95ab98acfd4ba3fe7862d4b3f9d9d7b7d3f40824

**Comment by samoht** [comment] 2018-09-25 14:30
Which version of `dune-release` are you running? I thought I fixed this but apparently not...

It still not very clear to me when `odoc` is creating a subdir and when it isn't. /cc @Anton and/or @rizo for help :-)

**Comment by anuragsoni** [comment] 2018-09-25 14:37
That particular commit was created with dune-release 1.0

I tried with odoc `1.2.0` and by pinning it to master but its the same behavior in either case. I can try taking a look at this if someone can point where to start 😄. I don't know too much about how odoc works.

**Comment by samoht** [comment] 2018-09-25 14:53
The function doing the build and copying the result to the right place is https://github.com/samoht/dune-release/blob/master/bin/publish.ml#L10-L20

**Comment by aantron** [comment] 2018-09-25 15:03
@samoht The directory structure is created by Dune, not odoc, so cc @rgrinberg.

The directory structure has changed at some point in the development of Dune/Jbuilder, but I am not very familiar with the details. Not sure if this is the problem here.

**Comment by rgrinberg** [comment] 2018-09-25 15:18
Yes but the change was ages ago and the old structure lasted for maybe 1 point release of dune. In any case, this is yet another argument for making dune-release a part of dune. One less thing to keep in sync :)

**Comment by anuragsoni** [comment] 2018-09-26 01:02
https://github.com/anuragsoni/color/commit/f209a500112fbf4ae267bcfdb67d2947aa2e053f

Adding a folder name in the doc url seems to help. Github pages can pick it up since the foldername doesn't start with an underscore.

**Comment by anuragsoni** [comment] 2018-09-26 01:30
The value for the documentation URI needs to be of the form "$SCHEME://$USER.github.io/$REPO/$PATH". When setting the PATH to an empty value, `dune-release` is just copying the `_html` folder without renaming it. Github-pages doesn't pick it up for reasons I described above. Should a default value for `PATH` be picked so we don't up in such a situation?

This could also be a candidate for a check that can be added to the `lint` step as picking a path that starts with an underscore will not work with github pages or any other static site host that uses jekyll.

**Comment by samoht** [comment] 2018-09-28 10:15
I think this should be fixed by #97 as well

**Comment by anuragsoni** [comment] 2018-09-28 12:33
@samoht I don't believe #97 fixes this issue. I think the problem for this issue was: https://github.com/samoht/dune-release/blob/171e7b44513a98fa265c6e888fa200f75ad4fcd9/lib/pkg.ml#L324

When using a documentation URL like `https://anuragsoni.github.io/color/` in the opam file, the generated html directory `_html` is copied to the root level of gh-pages branch but its still named `_html` which results in github pages not picking it up.

**Comment by samoht** [comment] 2018-09-28 12:34
Ha yes sorry. Would you be able to send a patch (and maybe add a test) for this?

**Comment by anuragsoni** [comment] 2018-09-28 12:35
Sure. I'll make a pull request later today or by tomorrow. What behaviour would you expect here? Is this something that should be caught by the linter or should we pick a default that works with github-pages. I think picking a default that works with github-pages should be acceptable. What do you think?

**Comment by samoht** [comment] 2018-09-28 12:36
> I think picking a default that works with github-pages should be acceptable.

Yes that sounds good.

**Comment by samoht** [comment] 2018-10-16 15:40
With @dinosaure we found that the problem is https://knowledge.autodesk.com/support/smoke/troubleshooting/caas/sfdcarticles/sfdcarticles/The-cp-R-command-works-differently-on-Mac-OS-X-than-on-Linux.html

I'll remove the trailing '/' and hope it works on both platform..

**Comment by anuragsoni** [comment] 2018-10-16 15:52
Hmm, if i understand correctly, the current behavior of `cp -R _html/ .` copies the content of the _html folder to `.` and as a result everything works fine for github pages, whereas on linux a folder `_html` is put at the root. Wouldn't removing the trailing slash make the behavior on mac the same as linux and as a result break the behavior for both platforms?

**Comment by samoht** [comment] 2018-10-16 16:53
https://github.com/samoht/dune-release/pull/109/commits/626110a2c65876fadf411d760718a7485618afaa is not very efficient but it should properly fix the issue.

**Closed** 2018-10-16 17:08 UTC
Labels: bug

**Comment by anuragsoni** [comment] 2018-10-16 17:11
thanks

**Comment by samoht** [comment] 2018-10-16 17:14
If you are on Linux that would be great if you could confirm that the issue is properly solved (although as it seems to work for me, I doubt the os type will have any impact here, but who knows)
