### ISSUE TITLE
Incorrect branch when publishing distribution

### ISSUE THREAD

**Issue by mmottl** [samoht/dune-release#111] opened 2018-10-18 02:47 UTC
The following is part of the output of `dune-release publish distrib --verbosity=debug`:

```
dune-release: [EXEC:30081] ['git' '--git-dir' '.git' 'push' '--force'
                            'git@github.com:mmottl/gsl-ocaml.git'
                            '1.23.0-2-g0ad5974']
fatal: 1.23.0-2-g0ad5974 cannot be resolved to branch.
dune-release: [ERROR] run ['git' '--git-dir' '.git' 'push' '--force'
                           'git@github.com:mmottl/gsl-ocaml.git'
                      '1.23.0-2-g0ad5974']: exited with 128
```

The branch used by `dune-release` above contains an extra suffix `-2-g0ad5974` that doesn't exist.

**Comment by yannham** [comment] 2018-10-22 10:46
I had the same problem, I guess you tagged (through dune-release tag) the HEAD of your current branch, then tried to build the package, made some corrections and committed it, and built the package again. If that's the case I guess the problem is that the new HEAD does not correspond to the tag anymore: a workaround is to delete the tag (`git tag --delete YOURVERSION`), then create it again (`dune-release tag`) and the next build should generate a clean archive without an extra suffix.

**Comment by mmottl** [comment] 2018-10-22 15:55
@yannham Thanks for the hint, that's obviously what's going on.  I believe this used to work before, but now apparently it doesn't.  I'll just move the tag to the HEAD, since there hasn't been an actual release yet anyway.

**Comment by NathanReb** [comment] 2019-11-22 13:39
That is indeed what happened. I'm closing this as a workaround currently exists.

Please re-open if this is part of your workflow and turns out to be a blocker for using `dune-release`.

**Closed by NathanReb** 2019-11-22 13:39 UTC
